### ISSUE TITLE
Doesnt always show messages in popup

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/nicemessages#2]
Created a test module with a menu callback to a form. The form function is just a `dpm()` and a submit button. On navigating to the test URL, the message shows in popup. On page refresh, the normal page messages show. Flush all caches, and the "all caches cleared" message shows in popup, same with flush theme cache. Flushing any other cache (just to get a set message) and the "xxx cache cleared" message shows in normal page messages. If I naviagte to the module settings page, and either delete the default `admin/*` path or replace it with any other path, then save (the message should then popup since admin paths are not excluded anymore), I still get normal page messages.

Edit: tried on a demo site on BackdropCMS.org, and same behavior there.

**Comment by alanmels** [comment]
Thanks for the report. I need to run some additional tests to replicate the issue as it's working on my local dev environment. Not sure if it could be about the difference in PHP or anything else. Meanwhile, I'd appreciate if you could troubleshoot the issue on your end. Any relevant entries in the log?

**Comment by docwilmot** [comment]
No log messages and this happens local and in the Tugboat demo site. 
Fixed local by using `nicemessages_preprocess_layout()` instead of `nicemessages_theme_registry_alter()`.

**Comment by alanmels** [comment]
The `nicemessages_preprocess_layout()` didn't want to work for me, but `nicemessages_theme_registry_alter()` did. Did you just replace the function name or changes some part of the function? Could the difference be theme related? What theme you are using?

**Comment by docwilmot** [comment]
```
function nicemessages_preprocess_layout(&$variabless) {
  if (nicemessages_are_enabled()) {
    if (nicemessages_pages_visibility() == FALSE) {
      return;
    }
    nicemessages_set_messages();
  }
}
```

Basis, Bootstrap 5 Lite, and Seven for admin theme. And of course default settings on Tugboat.

**Comment by docwilmot** [comment]
Flush caches after changing the function of course.

**Comment by alanmels** [comment]
I've put both functions there just in case and unfortunately it works intermittently throughout a fresh Backdrop setup: doesn't work on node edits, for example. So I'm afraid there is more to troubleshoot. Because the $message variable was moved from hook_page_alter, it's not clear where exactly to intercept that variable now in Backdrop. Tried several different hooks, but the only one `nicemessages_theme_registry_alter` seemed to be working for me at the time, and now it's clear that it works partially.

**Comment by alanmels** [comment]
Please give a try to the latest dev as I've pushed some new lines in. I'm afraid the `hook_page_alter()` on Drupal 7 was one convenient place to alter the @message variable. Now we have to catch it in multiple different hooks like so:
```

/**
 * Implements hook_theme_registry_alter().
 */
function nicemessages_theme_registry_alter(&$theme_registry) {
  if (nicemessages_are_enabled()) {
    if (nicemessages_pages_visibility() == FALSE) {
      return;
    }
    nicemessages_set_messages();
  }
}

/**
 * Implements hook_preprocess_layout().
 */
function nicemessages_preprocess_layout(&$variabless) {
  if (nicemessages_are_enabled()) {
    if (nicemessages_pages_visibility() == FALSE) {
      return;
    }
    nicemessages_set_messages();
  }
}

/**
 * Implements hook_node_view().
 */
function nicemessages_node_view(Node $node, $view_mode, $langcode) {
  if (nicemessages_are_enabled()) {
    if (nicemessages_pages_visibility() == FALSE) {
      return;
    }
    nicemessages_set_messages();
  }
}
```

Also I had to add the same block of code to:

`function nicemessages_init() {`

and now it seems to be working everywhere. However, I am not sure where else it could fail, so we will keep finding such places and use respective hooks to introduce nicemessages or alternatively find one ideal place where to tamper with $message variable.

**Comment by alanmels** [comment]
Found the single point of tampering the variables. Was not obvious at once since it's a different approach than on D7:

```
/**
 * Implements hook_theme_registry_alter().
 * @param $theme_registry
 */
function nicemessages_theme_registry_alter(&$theme_registry) {
  $theme_registry['status_messages']['function'] = 'nicemessages_set_messages';
}
```

It covers all occurrences of $messages. Please give a try to dev.
